Added more jam tools

diff --git a/tools/jrun b/tools/jrun
--- a/tools/jrun
+++ b/tools/jrun
@@ -13,7 +13,6 @@ fi
 
 # No need to edit below this line unless you find a bug!
 
-
 die() {
     printf '%s\n' "$1" >&2
     exit 1
@@ -21,40 +20,129 @@ die() {
 
 show_usage() {
     cat << EOF
+jrun program.jxe
+Runs only the J node of a device with program.jxe
+under the application name 'testapp'. To run under a different
+app name X, use the --app=X option. Use the --fog option to run at the
+J node at the fog level or --cloud option to run at the cloud level.
+
+By default, jrun uses a Redis server running at 127.0.0.1:6379 as the
+data store. The Redis server needs to be started before launching the
+application. To use a different Redis server use the --data option like
+the following command using a Redis at local port 7000.
+
+jrun program.jxe --data=127.0.0.1:7000
+
+To provide a set of tags to the program, use the following command.
+jrun program.jxe --tag="param1, param2"
+
 Usage: runj file.jxe [--app=appl_name] [--fog|--cloud]
-                            [--port=port_number] [--data=data-url]
+                            [--data=data-url]
                             [--tags=quoted_list_of_tags]
                             [--group=group_name]
-                            [--force]
 
-The runj command instantiates a J node from file.jxe (JAM executable).
-If no type (fog or cloud) specified, a device J node will be started.
-The --port option is useful to start multiple J nodes in the same machine.
-The runj command will start the MQTT broker in that port if the broker is not
-running at the time. The MQTT broker will continue to run after the application
-has completed execution. The --data option takes a URL pointing to the data
-depot (Redis instance) to be used by the jdata subsystem. The url could be
-as simple as an IP address (127.0.0.1) of the Redis instance (assuming default
-port).
-
-Use the --force option to reopen the executable file. This should be used after
-recompiling the JAMScript program. Use the --tags option to pass initial
-tags to the program (equivalent to a command line argument - a single string).
-If you want to start multiple device clusters (a cluster is a J node with its
-own set of C nodes), use the --group option. The J node and C nodes should have
-matching --group specification.
-
+The jrun command creates a run state in the $HOME/__jamrun folder.
 EOF
+}
+
+
+writegroup() {
+
+    local port=$1
+    local gname=$2
+
+    if [ -e $port ]; then
+        cat $gname > $port/group
+    else
+        die "Port directory is missing.."
+    fi
+}
+
+checkmosquitto() {
+
+    # Check the required commands..
+    if [ ! -e $MOSQUITTO ]; then
+        die "Mosquitto MQTT broker $MOSQUITTO not found. Set new location."
+    fi
+    if [ ! -e $MOSQUITTO_PUB ]; then
+        die "Mosquitto tools $MOSQUITTO_PUB not found. Set new location."
+    fi
+    if [ ! -e $TMUX ]; then
+        die "terminal multiplexor $TMUX not found. Set new location."
+    fi
+}
+
+startmqtt() {
+    local port=$1
+
+    # Check whether the MQTT server is running.. if not start it
+    $MOSQUITTO_PUB -p $port -t "test" -m "hello"
+    if [ $? -ne 0 ]; then
+        echo "MQTT is not running at $port"
+        echo "Attempting to start MQTT at $port"
+        $MOSQUITTO -p $port &
+    fi
+}
+
+dojamout() {
+    local type=$1
+    local pnum=$2
+
+    startmqtt $pnum
+
+    case $type in
+        cloud)
+            if [ -z "$tags" ]; then
+                node jamout.js --app=$app --cloud --port=$pnum --data=$data
+            else
+                node jamout.js --app=$app --cloud --port=$pnum --data=$data --tags=$tags
+            fi
+            ;;
+        fog)
+            if [ -z "$tags" ]; then
+                node jamout.js --app=$app --fog --port=$pnum --data=$data
+            else
+                node jamout.js --app=$app --fog --port=$pnum --data=$data --tags=$tags
+            fi
+            ;;
+        device)
+            if [ -z "$tags" ]; then
+                node jamout.js --app=$app --port=$pnum --data=$data
+            else
+                node jamout.js --app=$app --port=$pnum --data=$data --tags=$tags
+            fi
+            ;;
+    esac
+}
+
+
+# This is always scanning for a command with 'node'
+portavailable() {
+    local folder=$1
+    local port=$2
+
+    if [ -d $folder/$port ]; then
+        if [ -e $folder/$port/processId ]; then
+            local pid=`cat $folder/$port/processId`
+            if [ ! -z $pid ]; then
+                porttaken=`ps -p $pid | grep node | wc -l`
+            else
+                porttaken=0
+            fi
+        else
+            porttaken=0
+        fi
+    else
+        porttaken=0
+    fi
 }
 
 # Initialize all the option variables.
 app=testapp
-port=1883
 type=device
 data=127.0.0.1
-force=
 tags=
-group="."
+group="default"
 
 file=$1
 shift
@@ -69,13 +157,8 @@ if [ "$fext" != "jxe" ]; then
     die "Extension on $file is not .jxe"
 fi
 
-# Check the required commands..
-if [ ! -e $MOSQUITTO ]; then
-    die "Mosquitto MQTT broker $MOSQUITTO not found. Set new location."
-fi
-if [ ! -e $MOSQUITTO_PUB ]; then
-    die "Mosquitto tools $MOSQUITTO_PUB not found. Set new location."
-fi
+# Check whether mosquitto tools are there
+checkmosquitto
 
 
 while :; do
@@ -111,20 +194,6 @@ while :; do
             ;;
         --tags=)            # Handle the case of an empty
             die 'ERROR: "--tags" requires a non-empty option argument.'
-            ;;
-        -p|--port)           # Takes an option argument; ensure it has been specified.
-            if [ "$2" ]; then
-                port=$2
-                shift
-            else
-                die 'ERROR: "--port" requires a non-empty option argument.'
-            fi
-            ;;
-        --port=?*)
-            port=${1#*=}     # Delete everything up to "=" and assign the remainder.
-            ;;
-        --port=)            # Handle the case of an empty
-            die 'ERROR: "--port" requires a non-empty option argument.'
             ;;
         -d|--data)           # Takes an option argument; ensure it has been specified.
             if [ "$2" ]; then
@@ -168,9 +237,6 @@ while :; do
                 type="cloud"
             fi
             ;;
-        -r|--force)
-            force=1
-            ;;
         --)              # End of all options.
             shift
             break
@@ -193,34 +259,23 @@ fi
 
 if [ -e "$file" ]; then
 
-    # Check whether the MQTT server is running.. if not start it
-    $MOSQUITTO_PUB -p $port -t "test" -m "hello"
-    if [ $? -ne 0 ]; then
-        echo "MQTT is not running at " $port
-        echo "Attempting to start MQTT at" $port
-        $MOSQUITTO -p $port &
+    # Check whether the global __jamruns folder is there
+    jamfolder=$HOME"/__jamruns"
+    if [ ! -d $jamfolder ]; then
+        mkdir $jamfolder
     fi
-
     # Get the folder
     filenoext="${file%.*}"
-    folder=$filenoext"_"$app
+    folder=$HOME/__jamruns/$filenoext"_"$app
     if [ ! -d "$folder" ]; then
         mkdir $folder
     fi
 
     # unzip the executable in the folder and run it..
-    if [ -n "$force" ]; then
-        unzip $file -d $folder
-        if [ $? -ne 0 ]; then
-            die "Problem reading file: $file"
-        fi
-    else
-        if [ ! -e $folder/jamout.js ] && [ ! -e $folder/a.out ]; then
-            unzip $file -d $folder
-            if [ $? -ne 0 ]; then
-                die "Problem reading the file: $file"
-            fi
-        fi
+    # We are unzipping the copying the files no matter what!
+    unzip -oq $file -d $folder
+    if [ $? -ne 0 ]; then
+        die "Problem reading file: $file"
     fi
 
     cd $folder
@@ -235,25 +290,32 @@ if [ -e "$file" ]; then
         # execute the program.. we are in the folder..
         case $type in
             cloud)
-                if [ -z "$tags" ]; then
-                    node jamout.js --app=$app --cloud --port=$port --data=$data
-                else
-                    node jamout.js --app=$app --cloud --port=$port --data=$data --tags=$tags
-                fi
+                iport=9883
+                while [ : ]; do
+                    portavailable $folder $iport
+                    [[ $porttaken == 1 ]] || break
+                    ((iport++))
+                done
+                dojamout $type $iport
                 ;;
             fog)
-                if [ -z "$tags" ]; then
-                    node jamout.js --app=$app --fog --port=$port --data=$data
-                else
-                    node jamout.js --app=$app --fog --port=$port --data=$data --tags=$tags
-                fi
+                iport=5883
+                while [ : ]; do
+                    portavailable $folder $iport
+                    [[ $porttaken == 1 ]] || break
+                    ((iport++))
+                done
+                dojamout $type $iport
                 ;;
             device)
-                if [ -z "$tags" ]; then
-                    node jamout.js --app=$app --port=$port --data=$data
-                else
-                    node jamout.js --app=$app --port=$port --data=$data --tags="$tags"
-                fi
+                iport=1883
+                while [ : ]; do
+                    portavailable $folder $iport
+                    [[ $porttaken == 1 ]] || break
+                    ((iport++))
+                done
+                writegroup $iport $group
+                dojamout $type $iport
                 ;;
         esac
     else
